const { generatePdfFromHtml } = require('./src/services/ai.service');
const fs = require('fs');
(async () => {
  const html = `<html><body><h1>Test PDF</h1><p>This is a test PDF generated by Puppeteer.</p></body></html>`;
  try {
    const buffer = await generatePdfFromHtml(html);
    fs.writeFileSync('test_output.pdf', buffer);
    console.log('PDF written to test_output.pdf');
  } catch (err) {
    console.error('Error generating PDF:', err);
  }
})();
