const puppeteer = require('puppeteer');
(async () => {
  try {
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const page = await browser.newPage();
    const html = `<html><body><h1>Test PDF</h1><p>This is a test PDF generated by Puppeteer.</p></body></html>`;
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({ format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } });
    const fs = require('fs');
    fs.writeFileSync('C:/GENAI/scratch/test_output.pdf', pdf);
    console.log('PDF generated at C:/GENAI/scratch/test_output.pdf');
    await browser.close();
  } catch (err) {
    console.error('Error generating PDF:', err);
  }
})();
